// <auto-generated />
using System;
using CarRentalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRentalAPI.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20250228064409_UpdateCurrentMeterReadingOfCarToDefaultValue")]
    partial class UpdateCurrentMeterReadingOfCarToDefaultValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRentalAPI.Features.Booking.AggregateRoots.CarBooking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('UTC', NOW())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookingId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CarRentalAPI.Features.PickUpReturnRegistration.AggregateRoots.RegisterPickUpReturn", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('UTC', NOW())");

                    b.Property<string>("CustomerSSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PickUp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PickUpMeterReading")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Return")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReturnMeterReading")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegistrationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("RegisterPickUpReturns");
                });

            modelBuilder.Entity("CarRentalAPI.Shared.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('UTC', NOW())");

                    b.Property<int>("CurrentMeterReading")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40092e3e-625e-4262-8568-7c6fde1bb8f8"),
                            CategoryId = new Guid("5f6c717c-0f81-43dd-82a1-0fc6543e1607"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentMeterReading = 0,
                            Name = "Toyota Yaris - ABC 15",
                            RegistrationNumber = "ABC 15",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a4e0cd0a-c5d9-4f8a-98e1-fc7d0c7d4c6d"),
                            CategoryId = new Guid("6c8bfba9-99b4-4000-a54d-a52930a4aa7a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentMeterReading = 0,
                            Name = "Honda Civic - DEF 23",
                            RegistrationNumber = "DEF 23",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("502c070e-5245-4be8-b3af-18c0ce29298b"),
                            CategoryId = new Guid("9c614176-ad05-42f5-8b92-60465d1459f1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentMeterReading = 0,
                            Name = "Ford Explorer - HGU 45",
                            RegistrationNumber = "HGU 45",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("fb526a44-f175-4534-9091-2392e0420094"),
                            CategoryId = new Guid("07e34f61-e90c-47d3-b90c-a94607270864"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentMeterReading = 0,
                            Name = "Chrysler Pacifica - OEP 25",
                            RegistrationNumber = "OEP 25",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("ee56398f-38b7-4fce-9eb3-df84ba879f76"),
                            CategoryId = new Guid("6c8bfba9-99b4-4000-a54d-a52930a4aa7a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentMeterReading = 0,
                            Name = "Hyundai Elantra - SUE 09",
                            RegistrationNumber = "SUE 09",
                            Status = "Booked"
                        },
                        new
                        {
                            Id = new Guid("8a2637ae-41dd-4625-b347-bbb4ca85546c"),
                            CategoryId = new Guid("9c614176-ad05-42f5-8b92-60465d1459f1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentMeterReading = 0,
                            Name = "Jeep Grand Cherokee - LOE 25",
                            RegistrationNumber = "LOE 25",
                            Status = "Booked"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Shared.Entities.CarCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CarCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f6c717c-0f81-43dd-82a1-0fc6543e1607"),
                            Category = "Small"
                        },
                        new
                        {
                            Id = new Guid("6c8bfba9-99b4-4000-a54d-a52930a4aa7a"),
                            Category = "Medium"
                        },
                        new
                        {
                            Id = new Guid("88a2c05c-5505-4a3b-a04d-fa0b47a0e513"),
                            Category = "Large"
                        },
                        new
                        {
                            Id = new Guid("9c614176-ad05-42f5-8b92-60465d1459f1"),
                            Category = "SUV"
                        },
                        new
                        {
                            Id = new Guid("07e34f61-e90c-47d3-b90c-a94607270864"),
                            Category = "Minivan"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Shared.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('UTC', NOW())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0941b04f-e282-40ca-9435-cd10a1a78b4f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "+46 70 123 4567",
                            SSN = "123-45-6789"
                        },
                        new
                        {
                            Id = new Guid("59466a50-6844-41d4-b0d2-05ec732a8afa"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "+46 70 234 5678",
                            SSN = "987-65-4321"
                        },
                        new
                        {
                            Id = new Guid("683f140f-9811-4292-97c7-5cd063df6b1b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.johnson@example.com",
                            FirstName = "Emma",
                            LastName = "Johnson",
                            PhoneNumber = "+46 70 345 6789",
                            SSN = "111-22-3333"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Features.Booking.AggregateRoots.CarBooking", b =>
                {
                    b.HasOne("CarRentalAPI.Shared.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalAPI.Shared.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarRentalAPI.Features.PickUpReturnRegistration.AggregateRoots.RegisterPickUpReturn", b =>
                {
                    b.HasOne("CarRentalAPI.Features.Booking.AggregateRoots.CarBooking", "Booking")
                        .WithOne("RegisterPickUpReturn")
                        .HasForeignKey("CarRentalAPI.Features.PickUpReturnRegistration.AggregateRoots.RegisterPickUpReturn", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CarRentalAPI.Shared.Entities.Car", b =>
                {
                    b.HasOne("CarRentalAPI.Shared.Entities.CarCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarRentalAPI.Features.Booking.AggregateRoots.CarBooking", b =>
                {
                    b.Navigation("RegisterPickUpReturn");
                });
#pragma warning restore 612, 618
        }
    }
}
